### ISSUE TITLE
SyntaxError: Unexpected token import  - running in Jest

### ISSUE THREAD

**Issue by sorahn** [souporserious/react-popper#125]
Running jest with react-popper@0.9.2:

### Steps to reproduce the problem

1.  Create new application (create-react-app)
2.  Add [`react-bootstrap-typeahead`](https://github.com/ericgio/react-bootstrap-typeahead) (includes react-popper)
3.  Add `<Typeahead options={[]} />` to App.js
4.  Run `yarn test`

### What is the expected behavior?
Test Passes

### What went wrong?
```
 FAIL  src/App.test.js
  ● Test suite failed to run

    /Users/darylr/Github/popper-test/node_modules/react-popper/lib/Popper.js:13
    import { Component, createElement } from 'react';
    ^^^^^^

    SyntaxError: Unexpected token import

      at new Script (vm.js:51:7)
      at Object.<anonymous> (node_modules/react-bootstrap-typeahead/lib/Overlay.react.js:31:15)
```

### Any other comments?
from my yarn.lock file:
```
react-popper@^0.9.0:
  version "0.9.2"
  resolved "https://registry.yarnpkg.com/react-popper/-/react-popper-0.9.2.tgz#27a198e421e45e53261734dca28c6e57dd2c1604"
  dependencies:
    popper.js "^1.14.1"
    prop-types "^15.6.1"
```

I tried copying the example code from the react-popper home page, [here](https://github.com/souporserious/react-popper#usage) but was unable to even get that to work because of the following error:
```
96:12-21 'react-popper' does not contain an export named 'Reference'.
```

**Comment by FezVrasta** [comment]
About the homepage example, you are reading the documentation of the v1.x branch, you are  using the v0.x so you need to read this one:

https://github.com/souporserious/react-popper/tree/v0.x

About the error, it seems like your bundler doesn't support ES Modules but tries to import Popper.js from the `module` field, which is expressively dedicated to ES modules.

You may want to file an issue on the `react-bootstrap-typeahead` repository

**Comment by ericgio** [comment]
@FezVrasta: The error is coming from react-popper/lib/Popper.js, which uses ES module syntax. I'm using v0.9.2 and only see one version of the file there. Am I missing something?

**Comment by FezVrasta** [comment]
@ericgio if you use common JS you should use the `dist/react-popper.js` file.

**Comment by ericgio** [comment]
@FezVrasta: Thanks, I ended up figuring out the issue. My lib is also written with ES modules but the package is CJS. I was trying to tree shake the unused components and calling `react-popper/lib/Popper.js` in my .babelrc, which caused the problem.
